name: Android Debug CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build EnGeneric Debug APK
      run: |
        cd android
        ./gradlew clean assembleEnGenericDebug --stacktrace

    - name: Upload Debug APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: EnGenericDebug-apk
        path: android/app/build/outputs/apk/enGeneric/debug/*.apk
